# Generated by Django 5.1.4 on 2024-12-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('media_type', models.CharField(choices=[('image', 'Resim'), ('video', 'Video')], max_length=5, verbose_name='Medya Tipi')),
                ('image', models.ImageField(blank=True, upload_to='gallery/%Y/%m/', verbose_name='Resim')),
                ('video_url', models.URLField(blank=True, help_text="YouTube veya Vimeo URL'si", verbose_name='Video URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Galeri',
                'verbose_name_plural': 'Galeri',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
