# Generated by Django 5.1.4 on 2024-12-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, help_text='MP4, WebM formatlarını destekler', upload_to='gallery/videos/%Y/%m/', verbose_name='Video Dosyası'),
        ),
    ]
