# Generated by Django 5.1.4 on 2024-12-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='featured',
            new_name='is_featured',
        ),
        migrations.AddField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
