# Generated by Django 5.1.4 on 2024-12-14 17:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('short_description', models.TextField(verbose_name='Kısa Açıklama')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Görsel')),
                ('years_experience', models.PositiveIntegerField(default=20, verbose_name='Tecrübe (Yıl)')),
                ('completed_jobs', models.PositiveIntegerField(default=5000, verbose_name='Tamamlanan İşler')),
                ('happy_customers', models.PositiveIntegerField(default=1000, verbose_name='Mutlu Müşteriler')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
    ]
