# Generated by Django 5.1.4 on 2024-12-17 17:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_content_about_mission_about_story_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('icon', models.CharField(help_text='Örn: fa-key', max_length=50, verbose_name='Font Awesome İkon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('position', models.CharField(max_length=100, verbose_name='Pozisyon')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Fotoğraf')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ekip Üyesi',
                'verbose_name_plural': 'Ekip Üyeleri',
                'ordering': ['order'],
            },
        ),
    ]
