# Generated by Django 5.1.4 on 2024-12-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_teammember_bio_teammember_email_teammember_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='twitter',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Resim'),
        ),
    ]
