# Generated by Django 5.1.4 on 2024-12-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_remove_service_icon_remove_teammember_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(help_text='Hizmet için görsel', upload_to='services/', verbose_name='Resim'),
        ),
    ]
