# Generated by Django 5.1.4 on 2024-12-16 12:10

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('review', models.TextField(verbose_name='Yorum')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Puan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yorum Tarihi')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylı')),
            ],
            options={
                'verbose_name': 'Müşteri Yorumu',
                'verbose_name_plural': 'Müşteri Yorumları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200, verbose_name='Site Başlığı')),
                ('favicon', models.ImageField(blank=True, upload_to='settings/', verbose_name='Favicon')),
                ('logo', models.ImageField(blank=True, upload_to='settings/', verbose_name='Logo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('analytics_code', models.TextField(blank=True, verbose_name='Analytics Kodu')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='MediaMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('source', models.CharField(max_length=100, verbose_name='Kaynak')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('publish_date', models.DateField(verbose_name='Yayın Tarihi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, upload_to='media_mentions/%Y/%m/', verbose_name='Görsel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Basın Haberi',
                'verbose_name_plural': 'Basın Haberleri',
                'ordering': ['order', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('read', 'Okundu'), ('replied', 'Yanıtlandı'), ('spam', 'Spam')], default='new', max_length=10, verbose_name='Durum')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Ürün Görseli')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('stock', models.IntegerField(verbose_name='Stok Durumu')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Satışta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-created_at'],
            },
        ),
    ]
