# Generated by Django 5.1.4 on 2024-12-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('title', models.CharField(max_length=200, verbose_name='Yorum Başlığı')),
                ('review', models.TextField(verbose_name='Yorum')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Puan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yorum Tarihi')),
                ('approved', models.BooleanField(default=False, verbose_name='Onaylı')),
            ],
            options={
                'verbose_name': 'Müşteri Yorumu',
                'verbose_name_plural': 'Müşteri Yorumları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('source', models.CharField(max_length=100, verbose_name='Kaynak')),
                ('url', models.URLField(verbose_name='URL')),
                ('publication_date', models.DateField(verbose_name='Yayın Tarihi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, upload_to='media_mentions/%Y/%m/', verbose_name='Görsel')),
            ],
            options={
                'verbose_name': 'Basın Bahsetmesi',
                'verbose_name_plural': 'Basın Bahsetmeleri',
                'ordering': ['-publication_date'],
            },
        ),
    ]
