# Generated by Django 5.1.4 on 2024-12-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_carouselslide_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPreview',
        ),
        migrations.DeleteModel(
            name='CustomerReview',
        ),
        migrations.DeleteModel(
            name='MediaMention',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
