# Generated by Django 5.1.4 on 2024-12-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='Resim'),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='Anonim', max_length=100, verbose_name='Ad Soyad'),
        ),
    ]
