# Generated by Django 5.1.4 on 2024-12-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_user_review_image_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default=' ', max_length=100, verbose_name='Ad Soyad'),
        ),
    ]
