# Generated by Django 5.1.4 on 2024-12-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi'),
        ),
    ]
